application: sicher-eiel
version: 1
runtime: go
api_version: go1

handlers:
- url: /backend.*
  script: _go_app
  login: admin

- url: /sites.*
  script: _go_app
  login: admin

- url: /.*
  script: _go_app
